// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKhvb26B0948bmD2BaMIleZrLSAOJcCiU',
    appId: '1:754025713890:web:5da14ec47ded51fb5c4ebb',
    messagingSenderId: '754025713890',
    projectId: 'appvellum',
    authDomain: 'appvellum.firebaseapp.com',
    storageBucket: 'appvellum.firebasestorage.app',
    measurementId: 'G-7HELFNBLFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBURocKyoZKQuYrz49-SXwxmD_lkfYZw',
    appId: '1:754025713890:android:cc0a78e48749dd6a5c4ebb',
    messagingSenderId: '754025713890',
    projectId: 'appvellum',
    storageBucket: 'appvellum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYAteX8RlJHf39tyNl5Dku9z-QfKf_98',
    appId: '1:754025713890:ios:cd6a0b27e97ff7685c4ebb',
    messagingSenderId: '754025713890',
    projectId: 'appvellum',
    storageBucket: 'appvellum.firebasestorage.app',
    iosClientId: '754025713890-gtqot9heacce08geinc51lpk1sgg8at5.apps.googleusercontent.com',
    iosBundleId: 'com.vexorabyte.vellum',
  );
}
